In [ ]:
import numpy as np

Parameters

In [ ]:
# learning rate
alpha = 0.1

In [ ]:
# Initailize Weights and biases
def init_parameters(input_size,hidden_size):
    # Initiallize weights and bias from normal distribution
    w = np.random.normal(0, 1, size=(input_size,hidden_size))
    b = np.random.normal(0,1)

    return w, b

In [ ]:
# Sigmoid Function
def sigmoid(x):
    z = 1/(1+np.exp(-x))
    return z

In [ ]:
# Foward pass function
def forward(x, w, b):
    predictions = np.dot(x, w) + b
    z = sigmoid(predictions)
    y_hat = (z > 0.5).astype(int)

    return y_hat

In [ ]:
# calculate cost or loss
def compute_loss(y_hat, y):
    J = (y_hat-y)
    return J

In [ ]:
# derivative of w w.r.t x
def grad_w(J, x):
    dw = 1/J.shape[0] * np.sum(J*x)
    return dw

# derivative of w w.r.t x
def grad_b(J):
    db = 1/J.shape[0] * np.sum(J)
    return db

# backpropagation function
def backward(J, x, w, b):
    # Calculate gradients
    dw = grad_w(J, x.T)
    db = grad_b(J)

    # Update weights
    w = w - alpha * dw
    b = b - alpha * db

    return w, b

In [ ]:
# train function
def train(x=None, y=None, alpha=0.1, epochs=100):
    # Set size of input and hidden layers neurons according to data
    input_size = X.shape[0]
    hidden_size = Y.shape[1]

    # weights initiallize
    w, b = init_parameters(input_size,hidden_size)

    # Run model for training
    for epoch in range(epochs):
        y_hat = forward(x.T, w, b)
        J = compute_loss(y_hat, y)
        w, b = backward(J, x, w, b)

    return w,b

In [ ]:
# test function
def test(x, w, b):
    y_hat = forward(x.T, w, b)
    return y_hat

ANN for AND

In [ ]:
# Dataset
X = np.array([[0,0,1,1],
              [0,1,0,1]])
Y = np.array([0,0,0,1])
Y = Y[:, np.newaxis]


test_X = np.array([ [1,0,1,1],
                    [1,1,0,1]])

In [ ]:
w, b = train(X, Y, epochs=100)
test(test_X, w, b)


array([[1],
       [0],
       [1],
       [1]])

ANN for OR

In [ ]:
# Dataset
X = np.array([[0,0,1,1],
              [0,1,0,1]])
Y = np.array([0,1,1,1])
Y = Y[:, np.newaxis]


test_X = np.array([ [1,0,0,0],
                    [1,1,0,1]])

In [ ]:
w, b = train(X, Y, epochs=100)
test(test_X, w, b)


array([[1],
       [1],
       [0],
       [1]])

ANN for Not

In [ ]:
# Dataset
X = np.array([[0,1]])
Y = np.array([1,0])

Y = Y[:, np.newaxis]


test_X = np.array([[1,0,1,1]])

In [ ]:
w, b = train(X, Y, epochs=100)
test(test_X, w, b)

array([[0],
       [1],
       [0],
       [0]])

ANN for NOR Gate

In [ ]:
# Dataset
X = np.array([[0,0,1,1],
              [0,1,0,1]])
Y = np.array([1,0,0,0])
Y = Y[:, np.newaxis]


test_X = np.array([ [1,0,0,0],
                    [1,1,0,1]])

In [ ]:
w, b = train(X, Y, epochs=100)
test(test_X, w, b)

array([[0],
       [0],
       [1],
       [0]])

ANN for NAND

In [ ]:
# Dataset
X = np.array([[0,0,1,1],
              [0,1,0,1]])
Y = np.array([1,1,1,0])
Y = Y[:, np.newaxis]


test_X = np.array([ [1,0,0,1],
                    [1,1,0,1]])

In [ ]:
w, b = train(X, Y, epochs=100)
test(test_X, w, b)

array([[1],
       [1],
       [1],
       [1]])

ANN for XNOR Gate

In [ ]:
def init_parameters_2n(input_size, hidden_size, output_size=1):
    # Initialize weights and bias for the hidden layer
    w_hidden = np.random.normal(0, 1, size=(input_size, hidden_size))
    b_hidden = np.random.normal(0, 1, size=(1, hidden_size))  # Updated to match the shape of w_hidden

    # Initialize weights and bias for the output layer
    w_output = np.random.normal(0, 1, size=(hidden_size, output_size))
    b_output = np.random.normal(0, 1, size=(1, output_size))  # Updated to match the shape of w_output

    return w_hidden, b_hidden, w_output, b_output


In [ ]:
# Forward pass function
def forward_n2(x, w_hidden, b_hidden, w_output, b_output):
    z1 = np.dot(x, w_hidden) + b_hidden
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w_output) + b_output
    a2 = sigmoid(z2)

    y_hat = (a2 > 0.5).astype(int)

    return y_hat, a2, a1

# Backpropagation function
def backward_n2(x, y, a2, a1, w_output, b_output, w_hidden, b_hidden, alpha):
    # Calculate the error
    J = -(y - a2) * (a2 * (1 - a2))

    # Update weights and biases for the output layer
    dw_output = np.dot(a1.T, J)
    db_output = np.sum(J, axis=0, keepdims=True)
    w_output = w_output - alpha * dw_output
    b_output = b_output - alpha * db_output

    # Calculate the error for the hidden layer
    J_hidden = np.dot(J, w_output.T) * (a1 * (1 - a1))

    # Update weights and biases for the hidden layer
    dw_hidden = np.dot(x.T, J_hidden)
    db_hidden = np.sum(J_hidden, axis=0, keepdims=True)
    w_hidden = w_hidden - alpha * dw_hidden
    b_hidden = b_hidden - alpha * db_hidden

    return w_hidden, b_hidden, w_output, b_output


In [ ]:
# train function
def train_n2(x=None, y=None, alpha=0.1, epochs=1000):
    input_size, hidden_size = 2, 2
    w_hidden, b_hidden, w_output, b_output = init_parameters_2n(input_size, hidden_size)
    for epoch in range(epochs):
        y_hat, a2, a1 = forward_n2(X.T, w_hidden, b_hidden, w_output, b_output)
        w_hidden, b_hidden, w_output, b_output = backward(X.T, Y, a2, a1, w_output, b_output, w_hidden, b_hidden, alpha)
    return w_hidden, b_hidden, w_output, b_output

In [ ]:
def test_n2(test_X, w_hidden, b_hidden, w_output, b_output):
    results, _, _ = forward_n2(test_X.T, w_hidden, b_hidden, w_output, b_output)
    return results

In [ ]:
# Dataset
X = np.array([[0,0,1,1],
              [0,1,0,1]])
Y = np.array([1,0,0,1])
Y = Y[:, np.newaxis]


test_X = np.array([ [1,1,0,0],
                    [0,1,0,1]])

In [ ]:
w_hidden, b_hidden, w_output, b_output = train_n2(X, Y, epochs=10000)

In [ ]:
test_n2(test_X, w_hidden, b_hidden, w_output, b_output)


array([[0],
       [1],
       [1],
       [0]])

ANN for XOR

In [ ]:
# Dataset
X = np.array([[0,0,1,1],
              [0,1,0,1]])
Y = np.array([0,1,1,0])
Y = Y[:, np.newaxis]


test_X = np.array([ [1,1,0,0],
                    [0,1,0,1]])

In [ ]:
w_hidden, b_hidden, w_output, b_output = train_n2(X, Y, epochs=10000)

In [ ]:
test_n2(test_X, w_hidden, b_hidden, w_output, b_output)


array([[1],
       [0],
       [0],
       [1]])